try {
  add();
} catch (err) {
  console.log(err.message);
}
console.log("Hello!");
